# Generated by Django 2.0a1 on 2017-10-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreworkVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('subject', models.CharField(choices=[('calc', 'Calculus'), ('stats', 'Statistics')], db_index=True, max_length=4)),
                ('video_link', models.CharField(max_length=100)),
                ('class_num', models.SmallIntegerField()),
                ('video_num', models.SmallIntegerField(default=1)),
                ('slug', models.SlugField(unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
    ]
