# Generated by Django 2.0a1 on 2017-10-10 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_unit'),
        ('videos', '0003_videometadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='preworkvideo',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='classes.Unit'),
            preserve_default=False,
        ),
    ]
