# Generated by Django 2.0a1 on 2017-10-10 07:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_subjects(apps, schema_editor):
    Subject = apps.get_model('classes', 'Subject')
    db_alias = schema_editor.connection.alias
    Subject.objects.using(db_alias).bulk_create([
        Subject(name='stats', grade=12),
        Subject(name='calc', grade=12)
    ])


def delete_subjects(apps, schema_editor):
    Subject = apps.get_model('classes', 'Subject')
    db_alias = schema_editor.connection.alias
    Subject.objects.using(db_alias).filter(name='stats').delete()
    Subject.objects.using(db_alias).filter(name='calc').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('calc', 'Calculus'), ('stats', 'Statistics')], db_index=True, max_length=5)),
                ('announcement', models.TextField(blank=True)),
                ('grade', models.IntegerField(default=12)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classdate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Subject'),
        ),
        migrations.AlterField(
            model_name='classdate',
            name='day',
            field=models.IntegerField(db_index=True),
        ),
        migrations.RunPython(create_subjects, delete_subjects)
    ]
