# Generated by Django 2.0a1 on 2017-10-18 18:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_subjects(apps, schema_editor):
    Subject = apps.get_model('classes', 'Subject')
    db_alias = schema_editor.connection.alias
    Subject.objects.using(db_alias).bulk_create([
        Subject(name='stats', grade=12),
        Subject(name='calc', grade=12)
    ])


def create_default_unit(apps, schema_editor):
    Unit = apps.get_model('classes', 'Unit')
    Subject = apps.get_model('classes', 'Subject')
    db_alias = schema_editor.connection.alias
    subj = Subject.objects.get(id=1)
    unit = Unit(name='default unit', subject=subj)
    unit.save(using=db_alias)


def delete_default_subjects(apps, schema_editor):
    Subject = apps.get_model('classes', 'Subject')
    db_alias = schema_editor.connection.alias
    Subject.objects.using(db_alias).filter(name='stats').delete()
    Subject.objects.using(db_alias).filter(name='calc').delete()


def delete_default_unit(apps, schema_editor):
    Unit = apps.get_model('classes', 'Unit')
    db_alias = schema_editor.connection.alias
    Unit.objects.using(db_alias).filter(name='default unit').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(db_index=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('calc', 'Calculus'), ('stats', 'Statistics')], db_index=True, max_length=50, unique=True)),
                ('grade', models.IntegerField(default=12)),
                ('announcement', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('performance_task_date', models.DateField(default=datetime.date.today)),
                ('number', models.IntegerField(default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classdate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Subject'),
        ),
        migrations.RunPython(create_default_subjects, delete_default_subjects),
        migrations.RunPython(create_default_unit, delete_default_unit),
    ]
