# Generated by Django 2.0a1 on 2017-10-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='classdate',
            name='day',
            field=models.IntegerField(db_index=True),
        ),
    ]
