# Generated by Django 2.0a1 on 2017-10-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('calc', 'Calculus'), ('stats', 'Statistics')], db_index=True, max_length=5, unique=True),
        ),
    ]
