# Generated by Django 2.0a1 on 2017-10-10 21:05

from django.db import migrations, models
import django.db.models.deletion


def create_default_unit(apps, schema_editor):
    Unit = apps.get_model('classes', 'Unit')
    Subject = apps.get_model('classes', 'Subject')
    db_alias = schema_editor.connection.alias
    subj = Subject.objects.get(id=1)
    unit = Unit(name='default unit', subject=subj)
    unit.save(using=db_alias)


def delete_default_unit(apps, schema_editor):
    Unit = apps.get_model('classes', 'Unit')
    db_alias = schema_editor.connection.alias
    Unit.objects.using(db_alias).filter(name='default unit').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_subject_name_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Subject')),
            ],
        ),
        migrations.RunPython(create_default_unit, delete_default_unit),
    ]
