# Generated by Django 2.0a1 on 2017-10-11 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('calc', 'Calculus'), ('stats', 'Statistics')], db_index=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='performance_task_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
