# Generated by Django 2.0a1 on 2017-10-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20171011_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classdate',
            options={'get_latest_by': 'date', 'ordering': ['-date']},
        ),
    ]
